### ISSUE TITLE
Error. GPT-3.5-Turbo don't work.

### ISSUE THREAD

**Issue by klauskobald** [Metim0l/free-gpt-engineer#2]
Any idea how to solve that problem?
Error. GPT-3.5-Turbo don't work.

**Comment by Metim0l** [comment]
I solved this problem 🙃

**Comment by Metim0l** [comment]
Hmm... Do you use fronted? Or clear backend?

**Comment by ravenquork** [comment]
same issue  i am using front end, deleted files first

**Comment by Metim0l** [comment]
It's a problem with the GPT website:

{
  "error": {
    "message": "You exceeded your current quota, please check your plan and billing details.",
    "type": "insufficient_quota",
    "param": null,
    "code": "insufficient_quota"
  }
}

I'll try to fix it.

**Comment by Metim0l** [comment]
It's a problem with the GPT website:

{
  "error": {
    "message": "You exceeded your current quota, please check your plan and billing details.",
    "type": "insufficient_quota",
    "param": null,
    "code": "insufficient_quota"
  }
}

If you know any another free GPT service or website, tell me please.

**Comment by ravenquork** [comment]
I paid for gpt 4 (20$) and now my s
gpt wont work at all

**Comment by ravenquork** [comment]
turbo is running ok but still get error message

**Comment by ravenquork** [comment]
turbo 3.5 is working fine
when i run the program with or without front end i get the message error turbo3.5 dont work

**Comment by klauskobald** [comment]
I use the commandline 
python main.py A
where A is the folder with the prompts
do not know if this is a front or backend

when the query to https://ai.chatgpt.org.uk is made, what credentials are being used?

**Comment by Metim0l** [comment]
I fixed everything, the installation instructions can be found at README. 

If everything works, or something doesn't work, write here, please. 😅

**Comment by jontstaz** [comment]
Is the free API only for GPT3.5 or does it have GPT4 as well?

**Comment by Metim0l** [comment]
GPT-4 paid, free only GPT-3.5
