### ISSUE TITLE
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by GuardianAngelWw** [Metim0l/free-gpt-engineer#5]
"Traceback (most recent call last):
  File "/home/runner/free-gpt-engineer/freegptmanager.py", line 4, in <module>
    from PyQt5.QtWidgets import QApplication, QFileSystemModel, QTreeView, QWidget, QVBoxLayout, QPushButton, QTextEdit, QMessageBox, QMainWindow, QDialog, QToolBar, QFileDialog
ImportError: libGL.so.1: cannot open shared object file: No such file or directory"

**Comment by MrCry0** [comment]
@GuardianAngelWw https://gprivate.com/666tu
